import nationalities from "@/data/nationalities.json"
import timezones from "@/data/timezones.json"

export const LearnerOnboardingConstants = {
    title: "Enroll a learner",
    description:
        "Thank you for your interest in joining Melody Wings. Fill out the form below and we'll get you a good fit.",
};

// Parent/Guardian Information Fields
const ParentGuardianFields: FormField[] = [
    {
        id: "parent_first_name",
        label: "First Name",
        inputType: "text",
        placeholder: "Enter First Name",
        gridCols: 1,
    },
    {
        id: "parent_last_name",
        label: "Last Name",
        inputType: "text",
        placeholder: "Enter Last Name",
        gridCols: 1,
    },
    {
        id: "relationship_to_learner",
        label: "Relationship to the Learner",
        inputType: "select",
        placeholder: "Select relationship",
        gridCols: 1,
        inputClassName: "!w-[49%]",
        className: "!w-[49%]",
        options: [
            { label: "Parent", value: "parent" },
            { label: "Guardian", value: "guardian" },
            { label: "Other", value: "other" },
        ],
    },
    {
        id: "",
        inputType: "parent",
    },
    {
        id: "parent_email",
        label: "Email address",
        inputType: "text",
        placeholder: "abc@example.com",
        gridCols: 1,
    },
    {
        id: "parent_contact_number",
        label: "Your contact number",
        sublabel: "(with country code)",
        inputType: "contact-input",
        placeholder: "Enter Email ID",
        sublabelAlignment: "right",
        gridCols: 1,
        disabled: false,
    },
    {
        id: "parent_address",
        label: "Address",
        inputType: "textarea",
        placeholder: "Type address here",
        gridCols: 2,
        inputClassName: "w-[49%]",
    }
];

// Learner's Personal Information Fields
const LearnerPersonalFields: FormField[] = [
    {
        id: "learner_first_name",
        label: "First Name",
        inputType: "text",
        placeholder: "Enter First Name",
        gridCols: 1,
        required: true,
    },
    {
        id: "learner_last_name",
        label: "Last Name",
        inputType: "text",
        placeholder: "Enter Last Name",
        gridCols: 1,
        required: true,
    },
    {
        id: "learner_date_of_birth",
        label: "Date of Birth",
        inputType: "birthdatepicker",
        placeholder: "MM/DD/YYYY",
        gridCols: 1,
        required: true,
        birthDatePicker: { minAge: 0, maxAge: 100 },
    },
    {
        id: "learner_gender",
        label: "Gender",
        inputType: "radio",
        options: [
            { label: "Male", value: "male" },
            { label: "Female", value: "female" },
            { label: "Prefer not to reveal", value: "not_specified" },
        ],
        gridCols: 1,
        required: true,
    },
    {
        id: "learner_preferred_pronoun",
        label: "Preferred Pronoun",
        inputType: "select",
        placeholder: "Select Pronoun",
        options: [
            { label: "He/Him", value: "he_him" },
            { label: "She/Her", value: "she_her" },
            { label: "They/Them", value: "they_them" },
        ],
        gridCols: 1,
        required: true,
    },
    {
        id: "learner_primary_language",
        label: "Primary Language",
        inputType: "async-select",
        endpoint: "languages",
        variant: "single",
        responseAsLabel: "language_name",
        responseAsValue: "language_name",
        placeholder: "Select language",
        gridCols: 1,
        required: true,
    },
    {
        parent: "learner_contact_details",
        id: "email",
        label: "Email Address",
        inputType: "text",
        placeholder: "Enter email",
        gridCols: 1,
        disabled: true,
        required: true,
    },
    {
        parent: "learner_contact_details",
        id: "contact_number",
        label: "Contact Number",
        inputType: "contact-input",
        sublabelAlignment: "right",
        gridCols: 1,
        disabled: false,
        required: true,
    },
    {
        parent: "learner_contact_details",
        id: "zip_code",
        label: "Zip Code",
        inputType: "text",
        placeholder: "Enter Zip Code",
        gridCols: 1,
        required: true,
    },
    {
        parent: "learner_contact_details",
        id: "country",
        label: "Country",
        inputType: "select",
        placeholder: "Select Country",
        options: nationalities,
        showSearch: true,
        gridCols: 1,
        required: true,
    },
    {
        parent: "learner_contact_details",
        id: "timezone",
        label: "Time Zone",
        inputType: "select",
        placeholder: "Select time zone",
        showSearch: true,
        options: timezones,        
        gridCols: 1,
        inputClassName: "!w-full",
        required: true,
    },
];

// Disability-Specific Information Fields
const DisabilityInfoFields: FormField[] = [
    {
        id: "type_of_developmental_disability",
        label: "Type of Developmental Disability",
        sublabel: "(e.g., autism, down syndrome, ADHD, etc.)",
        inputType: "async-select",
        creatable: true,
        endpoint: "development_disabilities",
        variant: "single",
        responseAsLabel: "development_disability_name",
        responseAsValue: "development_disability_name",
        placeholder: "Select type",
        gridCols: 1,
        required: true,
    },
    {
        id: "level_of_support_needed",
        label: "Level of Support Needed",
        inputType: "radio",
        options: [
            { label: "Mild", value: "mild" },
            { label: "Moderate", value: "moderate" },
            { label: "Extensive", value: "extensive" },
        ],
        gridCols: 1,
        sublabel: " ",
        className: "w-full h-full mt-4",
        required: true,
    },
    {
        id: "assistive_device_used",
        label: "Assistive Devices Used",
        sublabel: "(E.g. , Hearing aids, Wheelchair)",
        inputType: "async-select",
        endpoint: "assistive_devices",
        variant: "single",
        creatable: true,
        responseAsLabel: "assistive_device_name",
        responseAsValue: "assistive_device_name",
        placeholder: "Select assistive devices",
        gridCols: 1,
        required: true,
    },
    {
        id: "communication_style",
        label: "Communication Style",
        sublabel: "(e.g., verbal, sign language, AAC device)",
        inputType: "async-select",
        endpoint: "communication_styles",
        variant: "single",
        creatable: true,
        responseAsLabel: "communication_style_name",
        responseAsValue: "communication_style_name",
        placeholder: "Select style",
        gridCols: 1,
        required: true,
    },
    {
        id: "description",
        label: "Description of Abilities and Strengths",
        inputType: "textarea",
        placeholder: "Describe here",
        gridCols: 2,
        required: true,
    },
    {
        id: "areas_of_support_needed",
        label: "Areas of Support Needed",
        sublabel: "(e.g., communication, motor skills, behavior, academic skills)",
        inputType: "async-select",
        creatable: true,
        endpoint: "areas_of_support",
        variant: "multi",
        responseAsLabel: "area_of_support_name",
        responseAsValue: "area_of_support_name",
        placeholder: "Select areas of support",
        gridCols: 1,
        required: true,
    },
    {
        id: "learning_styles",
        label: "Learning Style",
        sublabel: "(visual, auditory, hands-on, etc.)",
        inputType: "async-select",
        creatable: true,
        endpoint: "learning_styles",
        variant: "multi",
        responseAsLabel: "learning_style_name",
        responseAsValue: "learning_style_name",
        placeholder: "Select learning styles",
        gridCols: 1,
        required: true,
    },
];

// Education and Background Fields
const EducationBackgroundFields: FormField[] = [
    {
        id: "current_school",
        label: "Current School/Program",
        sublabel: "(name of school, grade level)",
        inputType: "text",
        placeholder: "Enter school name",
        gridCols: 1,
        required: true,
    },
    {
        id: "iep_plan_key",
        label: "IEP or 504 Plan",
        sublabel: "(if applicable, include key details or goals)",
        inputType: "text",
        placeholder: "(appropriate relative to developmental level)",
        gridCols: 1,
        required: true,
    },
    {
        id: "academic_strengths",
        label: "Academic Strengths",
        sublabel: "(subjects the child enjoys or does well in)",
        inputType: "select-creatable",
        variant: "multi",
        placeholder: "Describe strengths",
        gridCols: 1,
        disabled: false,
        options: [
            { label: "Math", value: "math" },
            { label: "Science", value: "science" },
            { label: "History", value: "history" },
            { label: "English", value: "english" },
            { label: "Others", value: "others" },
            { label: "N/A", value: "n_a" },
        ],
        required: true,
    },
    {
        id: "academic_challenges",
        label: "Academic Challenges",
        sublabel: "(subjects where the child may need extra support)",
        inputType: "select-creatable",
        variant: "multi",
        placeholder: "Describe what areas need extra support",
        gridCols: 1,
        disabled: false,
        options: [
            { label: "Difficulty with reading", value: "difficulty_with_reading" },
            { label: "Struggles with writing", value: "struggles_with_writing" },
            { label: "Trouble with math skills", value: "trouble_with_math_skills" },
            { label: "Short attention span", value: "short_attention_span" },
            {
                label: "Difficulty following instructions",
                value: "difficulty_following_instructions",
            },
            { label: "Challenges with memory", value: "challenges_with_memory" },
            { label: "Trouble staying organized", value: "trouble_staying_organized" },
            {
                label: "Difficulty understanding abstract concepts",
                value: "difficulty_understanding_abstract_concepts",
            },
            { label: "Slow processing speed", value: "slow_processing_speed" },
            {
                label: "Difficulty with fine motor skills",
                value: "difficulty_with_fine_motor_skills",
            },
            { label: "Trouble working in groups", value: "trouble_working_in_groups" },
            {
                label: "Difficulty transitioning between tasks",
                value: "difficulty_transitioning_between_tasks",
            },
            { label: "Challenges with problem-solving", value: "challenges_with_problem_solving" },
            { label: "Struggles with test-taking", value: "struggles_with_test_taking" },
            {
                label: "Sensitivity to sensory distractions",
                value: "sensitivity_to_sensory_distractions",
            },
            { label: "Difficulty managing time", value: "difficulty_managing_time" },
            {
                label: "Challenges with verbal expression",
                value: "challenges_with_verbal_expression",
            },
            { label: "Trouble with comprehension", value: "trouble_with_comprehension" },
            { label: "Difficulty staying motivated", value: "difficulty_staying_motivated" },
            {
                label: "Struggles with self-regulation during tasks",
                value: "struggles_with_self_regulation_during_tasks",
            },
            { label: "Others", value: "others" },
            { label: "N/A", value: "n_a" },
        ],
        required: true,
    },
];

// Behavior and Social Skills Fields
const BehaviorSocialFields: FormField[] = [
    {
        id: "communication_preferences",
        label: "Communication Preferences",
        sublabel: "(visual, nonverbal, assistive devices)",
        inputType: "select-creatable",
        variant: "multi",
        placeholder: "Enter here",
        gridCols: 1,
        options: [
            { label: "Visual", value: "visual" },
            { label: "Nonverbal", value: "nonverbal" },
            { label: "Assistive Devices", value: "assistive_devices" },
            { label: "Others", value: "others" },
            { label: "N/A", value: "n_a" },
        ],
        required: true,
    },
    {
        id: "social_interaction_styles",
        label: "Social Interaction Style",
        sublabel: "(engaging, shy, prefers one-on-one group settings)",
        inputType: "select-creatable",
        variant: "multi",
        placeholder: "Enter here",
        gridCols: 1,
        options: [
            { label: "Engaging", value: "engaging" },
            { label: "Shy", value: "shy" },
            { label: "Prefers One-on-One", value: "prefers_one_on_one" },
            { label: "Prefers Group", value: "prefers_group" },
            { label: "Others", value: "others" },
            { label: "N/A", value: "n_a" },
        ],
        required: true,
    },
    {
        id: "behavioral_concerns",
        label: "Behavioral Concerns",
        sublabel: "(e.g., triggers, behaviors, suggested responses)",
        inputType: "select-creatable",
        variant: "multi",
        placeholder: "Enter here",
        gridCols: 1,
        options: [
            {
                label: "Difficulty in Social Interaction",
                value: "difficulty_in_social_interaction",
            },
            { label: "Delayed Communication Skills", value: "delayed_communication_skills" },
            { label: "Repetitive Behaviors", value: "repetitive_behaviors" },
            {
                label: "Difficulty in Adapting to Changes",
                value: "difficulty_in_adapting_to_changes",
            },
            {
                label: "Sensory Sensitivities (e.g., to Sound, Touch, or Light)",
                value: "sensory_sensitivities",
            },
            { label: "Short Attention Span", value: "short_attention_span" },
            { label: "Impulsivity", value: "impulsivity" },
            {
                label: "Difficulty in Understanding Social Cues",
                value: "difficulty_in_understanding_social_cues",
            },
            {
                label: "Aggressive Behaviors or Tantrums",
                value: "aggressive_behaviors_or_tantrums",
            },
            {
                label: "Self-Stimulatory Behaviors (e.g., Hand Flapping, Rocking)",
                value: "self_stimulatory_behaviors",
            },
            {
                label: "Difficulty in Maintaining Eye Contact",
                value: "difficulty_in_maintaining_eye_contact",
            },
            {
                label: "Fixation on Specific Objects or Topics",
                value: "fixation_on_specific_objects_or_topics",
            },
            {
                label: "Difficulty in Following Instructions",
                value: "difficulty_in_following_instructions",
            },
            {
                label: "Challenges in Emotional Regulation",
                value: "challenges_in_emotional_regulation",
            },
            { label: "High Levels of Anxiety or Fear", value: "high_levels_of_anxiety_or_fear" },
            {
                label: "Oppositional or Defiant Behaviors",
                value: "oppositional_or_defiant_behaviors",
            },
            {
                label: "Excessive Dependence on Routines or Rituals",
                value: "excessive_dependence_on_routines_or_rituals",
            },
            {
                label: "Easily Overwhelmed in Group Settings",
                value: "easily_overwhelmed_in_group_settings",
            },
            {
                label: "Difficulty in Forming Peer Relationships",
                value: "difficulty_in_forming_peer_relationships",
            },
            { label: "Hyperactivity or Hypoactivity", value: "hyperactivity_or_hypoactivity" },
            { label: "Others", value: "others" },
            { label: "N/A", value: "n_a" },
        ],
        required: true,
    },
    {
        id: "techniques_to_calm",
        label: "Techniques That Work",
        sublabel: "(e.g., positive reinforcement, breaks)",
        inputType: "select-creatable",
        variant: "multi",
        placeholder: "Enter here",
        gridCols: 1,
        options: [
            { label: "Provide a Quiet Space", value: "provide_a_quiet_space" },
            { label: "Use Deep Pressure", value: "use_deep_pressure" },
            { label: "Deep Breathing", value: "deep_breathing" },
            { label: "Play Calming Music", value: "play_calming_music" },
            { label: "Offer Fidget Toys", value: "offer_fidget_toys" },
            { label: "Keep Consistent Routine", value: "keep_consistent_routine" },
            { label: "Use Visual Aids", value: "use_visual_aids" },
            { label: "Express Through Art", value: "express_through_art" },
            { label: "Practice Grounding", value: "practice_grounding" },
            { label: "Physical Activity", value: "physical_activity" },
            { label: "Use Calm Voice", value: "use_calm_voice" },
            { label: "Give Comfort Item", value: "give_comfort_item" },
            { label: "Reduce Stimuli", value: "reduce_stimuli" },
            { label: "Simple Mindfulness", value: "simple_mindfulness" },
            { label: "Clear Instructions", value: "clear_instructions" },
            { label: "Others", value: "others" },
            { label: "N/A", value: "n_a" },
        ],
        required: true,
    },
];

// Interests and Hobbies Fields
const InterestsHobbiesFields: FormField[] = [
    {
        id: "interests",
        label: "Main Interests",
        sublabel: "(e.g., music, art, sports, technology)",
        inputType: "async-select",
        endpoint: "skills",
        creatable: true,
        variant: "multi",
        responseAsLabel: "skill_name",
        responseAsValue: "skill_name",
        placeholder: "Enter here",
        gridCols: 1,
        required: true,
    },
    {
        id: "extra_curricular_activities",
        label: "Extra Curricular Activities",
        sublabel: "(current or past participation)",
        inputType: "text",
        placeholder: "Enter here",
        responseType: "array",
        gridCols: 1,
        // options: [
        //     { label: "Sports (e.g., Football, Basketball)", value: "sports" },
        //     { label: "Music (e.g., Playing Instruments, Singing)", value: "music" },
        //     { label: "Art and Craft (e.g., Drawing, Painting)", value: "art_and_craft" },
        //     { label: "Drama and Theater", value: "drama_and_theater" },
        //     { label: "Debate and Public Speaking", value: "debate_and_public_speaking" },
        //     { label: "Dance (e.g., Ballet, Hip-Hop)", value: "dance" },
        //     { label: "Coding and Programming", value: "coding_and_programming" },
        //     { label: "Volunteering and Community Service", value: "volunteering_and_community_service" },
        //     { label: "Photography and Filmmaking", value: "photography_and_filmmaking" },
        //     { label: "Science Club or Robotics", value: "science_club_or_robotics" },
        // ],
        required: true,
    },
    {
        id: "favorite_activities",
        label: "Favorite Activities",
        sublabel: "(activities that motivate the child)",
        inputType: "text",
        placeholder: "Enter here",
        responseType: "array",
        gridCols: 1,
        // options: [
        //     { label: "Drawing and coloring", value: "drawing_and_coloring" },
        //     { label: "Listening to music", value: "listening_to_music" },
        //     { label: "Playing with sensory toys", value: "playing_with_sensory_toys" },
        //     { label: "Watching cartoons or movies", value: "watching_cartoons_or_movies" },
        //     { label: "Building with blocks or Legos", value: "building_with_blocks_or_legos" },
        //     { label: "Dancing or movement activities", value: "dancing_or_movement_activities" },
        //     { label: "Playing in water or sand", value: "playing_in_water_or_sand" },
        //     { label: "Doing puzzles", value: "doing_puzzles" },
        //     { label: "Reading books or looking at pictures", value: "reading_books_or_looking_at_pictures" },
        //     { label: "Gardening or planting seeds", value: "gardening_or_planting_seeds" },
        //     { label: "Playing on swings or slides", value: "playing_on_swings_or_slides" },
        //     { label: "Cooking or baking simple recipes", value: "cooking_or_baking_simple_recipes" },
        //     { label: "Crafting with paper and glue", value: "crafting_with_paper_and_glue" },
        //     { label: "Role-playing or pretend play", value: "role_playing_or_pretend_play" },
        //     { label: "Playing video games", value: "playing_video_games" },
        //     { label: "Doing simple science experiments", value: "doing_simple_science_experiments" },
        //     { label: "Exploring nature or going for walks", value: "exploring_nature_or_going_for_walks" },
        //     { label: "Blowing bubbles", value: "blowing_bubbles" },
        //     { label: "Singing songs or karaoke", value: "singing_songs_or_karaoke" },
        //     { label: "Playing board or card games", value: "playing_board_or_card_games" },
        // ],
        required: true,
    },
];

// Expectations and Goals Fields
const ExpectationsGoalsFields: FormField[] = [
    {
        id: "expected_goals",
        label: "Parent/Guardian’s Goals for the Child ",
        sublabel: "(e.g., improve social skills, academic progress, explore new hobbies)",
        inputType: "select-creatable",
        variant: "multi",
        placeholder: "Enter here",
        gridCols: 1,
        options: [
            { label: "Improve Communication", value: "improve_communication" },
            { label: "Build Friendships", value: "build_friendships" },
            { label: "Encourage Independence", value: "encourage_independence" },
            { label: "Manage Emotions", value: "manage_emotions" },
            { label: "Boost Confidence", value: "boost_confidence" },
            { label: "Support Learning", value: "support_learning" },
            { label: "Provide a Safe Home", value: "provide_a_safe_home" },
            { label: "Teach Life Skills", value: "teach_life_skills" },
            { label: "Encourage Activities", value: "encourage_activities" },
            { label: "Handle Sensory Issues", value: "handle_sensory_issues" },
            { label: "Work with Therapists", value: "work_with_therapists" },
            { label: "Show Love and Acceptance", value: "show_love_and_acceptance" },
            { label: "Teach Responsibility", value: "teach_responsibility" },
            { label: "Promote Good Health", value: "promote_good_health" },
            { label: "Support Hobbies", value: "support_hobbies" },
            { label: "Prepare for Changes", value: "prepare_for_changes" },
            { label: "Teach Problem-Solving", value: "teach_problem_solving" },
            { label: "Find Family Support", value: "find_family_support" },
            { label: "Learn Child’s Needs", value: "learn_childs_needs" },
            { label: "Teach Self-Advocacy", value: "teach_self_advocacy" },
            { label: "Others", value: "others" },
            { label: "N/A", value: "n_a" },
        ],
        required: true,
    },
    {
        id: "subjects_to_focus_on",
        label: "Specific Subject/Skill Preferences",
        sublabel: "(areas focus for tutoring or support)",
        inputType: "select-creatable",
        variant: "multi",
        options: [
            { label: "Math", value: "math" },
            { label: "Science", value: "science" },
            { label: "History", value: "history" },
            { label: "English", value: "english" },
            { label: "Others", value: "others" },
            { label: "N/A", value: "n_a" },
        ],
        placeholder: "Enter here",
        gridCols: 1,
        required: true,
    },
    {
        id: "preferred_volunteer_qualities",
        label: "Preferred Volunteer Qualities",
        sublabel: "(any specific traits the parent/guardian values in a tutor or mentor)",
        inputType: "select-creatable",
        variant: "multi",
        placeholder: "Enter here",
        gridCols: 1,
        options: [
            { label: "Patience", value: "patience" },
            { label: "Empathy", value: "empathy" },
            { label: "Compassion", value: "compassion" },
            { label: "Good Communication", value: "good_communication" },
            { label: "Adaptability", value: "adaptability" },
            { label: "Positivity", value: "positivity" },
            { label: "Attentiveness", value: "attentiveness" },
            { label: "Responsibility", value: "responsibility" },
            { label: "Flexibility", value: "flexibility" },
            { label: "Calm Under Pressure", value: "calm_under_pressure" },
            { label: "Kindness", value: "kindness" },
            { label: "Creativity", value: "creativity" },
            { label: "Good Listening Skills", value: "good_listening_skills" },
            { label: "Enthusiasm", value: "enthusiasm" },
            { label: "Teamwork Skills", value: "teamwork_skills" },
            { label: "Reliability", value: "reliability" },
            { label: "Emotional Stability", value: "emotional_stability" },
            { label: "Cultural Sensitivity", value: "cultural_sensitivity" },
            { label: "Sense of Humor", value: "sense_of_humor" },
            { label: "Willingness to Learn", value: "willingness_to_learn" },
            { label: "Others", value: "others" },
            { label: "N/A", value: "n_a" },
        ],
        required: true,
    },
    {
        id: "skill_level",
        label: "Skill Level",
        inputType: "radio",
        options: [
            { label: "Beginner", value: "beginner" },
            { label: "Intermediate", value: "intermediate" },
            { label: "Expert", value: "expert" },
        ],
        gridCols: 1,
        className: "w-full h-fit mt-4 gap-0 !mb-0",
        inputClassName: "w-full h-full  mt-4",
        required: true,
    },
];

// Additional Information Fields
const AdditionalInfoFields: FormField[] = [
    {
        id: "cultural_consideration",
        label: "Cultural/Religious Considerations",
        sublabel: "(if applicable for the program)",
        inputType: "text",
        placeholder: "Enter here",
        gridCols: 2,
        required: true,
    },
    {
        id: "other_concerns_or_requests",
        label: "Other Comments or Notes",
        sublabel: "(anything else the program should know)",
        inputType: "text",
        placeholder: "Enter here",
        gridCols: 2,
        required: true,
    },
    {
        id: "what_motivates_to_learn",
        label: "What motivates you to learn this subject? Do you have any specific goals or interests that you would like to focus in our lessons?",
        sublabel: "(anything else the program should know)",
        inputType: "textarea",
        placeholder: "Enter here",
        gridCols: 2,
        required: true,
    },
];

export const LearnerFormSections: FormSectionConfig[] = [
    {
        parent: "learner_personal_info",
        title: "Learner Information",
        fields: LearnerPersonalFields,
    },
    {
        parent: "parent_info",
        title: "Guardian Information",
        fields: ParentGuardianFields,
    },
    {
        title: "Profile Details",
        fields: [
            {
                parent: "learner_special_needs",
                title: "Disability-Specific Information",
                fields: DisabilityInfoFields,
            },
            {
                parent: "education",
                title: "Education and Background",
                fields: EducationBackgroundFields,
            },
            {
                parent: "social_skills",
                title: "Behavior and Social Skills",
                fields: BehaviorSocialFields,
            },
            {
                parent: "current_interests",
                title: "Current Interests and Hobbies",
                fields: InterestsHobbiesFields,
            },
            {
                parent: "learner_goals",
                title: "Expectations and Goals",
                fields: ExpectationsGoalsFields,
            }
        ],
        type: "card",
    },
    {
        parent: "additional_info",
        title: "Additional Information",
        fields: AdditionalInfoFields,
    },
    {
        title: "Upload Profile Picture",
        parent: null,
        fields: [
            {
                id: "profile_picture",
                label: "Learner's Profile Picture",
                inputType: "upload",
                required: false,
                gridCols: 1,
                variant: "file",
                fileType: "image/*",
            },
        ],
    },
    {
        title: "Consent",
        parent: "consent_and_permissions",
        fields: [
            {
                id: "photo_or_video_consent",
                label: "Photo/Video Consent",
                sublabel: "(for use in program materials or promotional content)",
                inputType: "radio",
                options: [
                    { label: "Yes", value: true },
                    { label: "No", value: false },
                ],
                required: false,
                gridCols: 1,
            },
            {
                id: "acknowledgement_of_program_policies",
                label: "Acknowledgment of Program Policies ",
                sublabel: "(Rules, Expectations, and Procedures)",
                options: [
                    { label: "Yes", value: true },
                    { label: "No", value: false },
                ],
                inputType: "radio",
                gridCols: 1,
            },
        ],
    },
];

export const LearnerThankyouCardConstants = {
    title: "Thank You for Enrolling in Melody Wings!",
    description:
        "We’re excited to have you join our community. Our team will review your details and get back to you shortly with the next steps. We appreciate your trust in us, and we look forward to helping you on this learning journey.",
};
