import "./globals.css";
import type { Metadata } from "next";
import Script from "next/script";
import { Poppins } from "next/font/google";
import RootLayoutClient from "./RootLayoutClient";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { GOOGLE_ANALYTICS_ID, GOOGLE_WEB_CLIENT_ID } from "@/definitions";

const poppins = Poppins({
    weight: ["300", "400", "500", "600", "700"],
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "MelodyWings",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <Script
                    src={`https://www.googletagmanager.com/gtag/js?id=${GOOGLE_ANALYTICS_ID}`}
                    strategy="afterInteractive"
                />
                <Script
                    id="gtag-init"
                    strategy="afterInteractive"
                    dangerouslySetInnerHTML={{
                        __html: `
                            window.dataLayer = window.dataLayer || [];
                            function gtag(){dataLayer.push(arguments);}
                            gtag('js', new Date());
                            gtag('config', '${GOOGLE_ANALYTICS_ID}');
                        `,
                    }}
                />
            </head>
            <body className={poppins.className}>
                <GoogleOAuthProvider clientId={GOOGLE_WEB_CLIENT_ID || ""}>
                    <RootLayoutClient>{children}</RootLayoutClient>
                </GoogleOAuthProvider>
            </body>
        </html>
    );
}
